### ISSUE TITLE
OpenVSX is down

### ISSUE THREAD

**Issue by AlexTugarev** [EclipseFdn/open-vsx.org#1252] opened 2022-09-28 06:43 UTC
Looks like https://open-vsx.org is down at the time of this issue. Search for extension doesn't work.

cc. @mbarbero @eclipsewebmaster
Could you check please and update https://www.eclipsestatus.io/ accordingly? Thank you!

**Comment by fredg02** [comment] 2022-09-28 07:26
https://open-vsx.org works again after a restart and increasing the number of production pods to 4.

**Comment by AlexTugarev** [comment] 2022-09-28 07:46
@fredg02, thanks for taking action swiftly! 
🙏🏻

**Comment by kineticsquid** [comment] 2022-09-28 17:13
Do we have an issue to track the root cause?

**Comment by ArthurSens** [comment] 2022-09-28 18:02
Hey 👋 -- Just letting you know that since around 50mins ago we're seeing errors again and it is still on going.

**Comment by ArthurSens** [comment] 2022-09-28 18:07
Friendly pinging @mbarbero @eclipsewebmaster just to make sure you know 🙂

**Comment by fredg02** [comment] 2022-09-28 19:02
Pods have been restarted.

**Comment by ArthurSens** [comment] 2022-09-29 19:11
Hey 👋 -- Just letting you know that since around 10 mins ago we started seeing failures again 😬

**Comment by fredg02** [comment] 2022-10-04 08:30
Closing.

**Closed by fredg02** 2022-10-04 08:30 UTC
