### ISSUE TITLE
OpenVSX is down again

### ISSUE THREAD

**Issue by utam0k** [EclipseFdn/open-vsx.org#1274] opened 2022-10-08 02:58 UTC
Looks like https://open-vsx.org is down at the time of this issue. @mbarbero @eclipsewebmaster
Could you check please and update https://www.eclipsestatus.io/ accordingly? Thank you!

```
Request failed: GET https://open-vsx.org/user (Bad Gateway)
```

**Comment by oorzc** [comment] 2022-10-08 13:13
I'm speechless and down again

**Comment by fredg02** [comment] 2022-10-08 14:23
Duplicate of #1270.

**Closed by fredg02** 2022-10-08 14:23 UTC
