### ISSUE TITLE
Claiming namespace embertooling

### ISSUE THREAD

**Issue by evoactivity** [EclipseFdn/open-vsx.org#2117] opened 2023-09-26 17:55 UTC
I'm a maintainer of the ember-tooling organisation https://github.com/ember-tooling/

We want to publish our extensions under the current namespace here https://open-vsx.org/namespace/embertooling but we are having a difficult time tracking down the original owner so we have access.

**Comment by kineticsquid** [comment] 2023-09-28 18:26
@evoactivity I can see you are a contributor to namespace `ember-tooling`, with no extensions published there. Namespace `embertooling` also exists because extension https://open-vsx.org/extension/embertooling/prettier-for-handlebars-vscode is currently auto-published: https://github.com/open-vsx/publish-extensions/blob/95896c6345c24494f8cb70a03dc481867467e945/extensions.json#L286.

What's the outcome you're looking for? E.g. one namespace you own, either `ember-tooling` or `embertooling` with, at least, the above extension published? Turn off the auto-publishing?

**Comment by evoactivity** [comment] 2023-09-29 02:39
I suppose if we can we remove `embertooling.prettier-for-handlebars-vscode` (it's deprecated and no longer recommended) that would work for us, we just have no idea what account has access to that namespace otherwise we would have just done that ourself. I'm happy to use the `ember-tooling` namespace. Ideally we would prefer only one namespace to exist to avoid confusion in the future.

**Comment by kineticsquid** [comment] 2023-10-02 15:39
@evoactivity One of my superpowers is the ability to un-publish an extension. Can you submit  a PR to remove the extension from the auto-publish list. Once that is merged and I can confirm it'll not be re-published, I'll un-publish the extension. Then I'll make you owner of either namespace `embertooling` or `ember-tooling`. Just let me know which.

**Comment by kineticsquid** [comment] 2023-10-06 14:39
@evoactivity ^^^^

**Comment by evoactivity** [comment] 2023-10-07 19:11
@kineticsquid sorry, I've been sick the last week, I will have time to do this next week.

**Comment by kineticsquid** [comment] 2023-10-13 17:47
@evoactivity Thanks for getting back to us on this. Hope you're feeling better!

**Comment by evoactivity** [comment] 2023-10-25 16:01
Slipped my mind sorry, I've created the PR to remove that addon.

https://github.com/open-vsx/publish-extensions/pull/717

The `ember-tooling` namespace would be ideal going forward. I might already be the owner of that space (I set it up on my account), not sure if something else needs to happen though.

**Comment by kineticsquid** [comment] 2023-10-31 17:40
@evoactivity I can see your PR has been merged. Confirming `embertooling` is the namespace you wish to own?

**Comment by evoactivity** [comment] 2023-10-31 23:17
Yes please :)

**Comment by kineticsquid** [comment] 2023-11-01 19:37
You are now the proud owner of the `embertooling` namespace!

**Closed by kineticsquid** 2023-11-01 19:37 UTC
Labels: namespace, granted

**Comment by evoactivity** [comment] 2023-11-03 02:45
Thanks @kineticsquid. Do you know when the `Prettier for Handlebars` extension will be unpublished?

**Comment by kineticsquid** [comment] 2023-11-03 21:14
@evoactivity Sorry, forgot about that. Done!
