### ISSUE TITLE
Delete an extension I uploaded

### ISSUE THREAD

**Issue by LeonN534** [EclipseFdn/open-vsx.org#2322] opened 2024-02-02 04:05 UTC
When I was creating the extension "Dark Minimalist" I uploaded a testing version of it. Once I finished, I uploaded the main version, but the other one is still there. I don't want people to install a wrong version of it, but it appears twice in the market place.
![2024-02-01-230041_317x239_scrot](https://github.com/EclipseFdn/open-vsx.org/assets/77511070/2a09024e-46aa-43aa-adbe-e4a8239d1fc9)
![2024-02-01-230312_900x320_scrot](https://github.com/EclipseFdn/open-vsx.org/assets/77511070/e52777f1-775c-4440-b19d-27a97f11d2ec)
When I click on the extension on the left, I get this message. That's why I want it to be deleted, so the main version will remain.
![2024-02-01-230326_620x306_scrot](https://github.com/EclipseFdn/open-vsx.org/assets/77511070/882b8e9a-6850-4fcc-b168-356f027ba44a)

**Comment by kineticsquid** [comment] 2024-02-13 01:30
@LeonN534 I removed version `1.0.0`, leaving `1.0.2`.

**Comment by LeonN534** [comment] 2024-02-16 05:52
Hello, I see that the extension is still on the marketplace.
![image](https://github.com/EclipseFdn/open-vsx.org/assets/77511070/4561ee17-21bd-4950-980e-5c7711c121b6)

**Comment by kineticsquid** [comment] 2024-02-18 20:06
Hmmm... reopening this one. Not sure what happened list time. It looks to be deleted correctly now. I'll wait for you to confirm @LeonN534 before I close this.

**Comment by LeonN534** [comment] 2024-02-18 21:14
The extension is no more shown. Now is deleted, but ehen searching for "dark minimalist" on the openvsx market, this error message appears![Screenshot_20240218-161152.png](https://github.com/EclipseFdn/open-vsx.org/assets/77511070/72b704b6-5246-49ea-969e-08b781788039)

**Comment by kineticsquid** [comment] 2024-02-19 19:49
@LeonN534 Are you still seeing this error? I am not. We sometimes see some quirky behavior due to caching, but if it's that it goes away after a bit.

**Comment by LeonN534** [comment] 2024-02-19 19:51
@kineticsquid ![Screenshot_20240219-145119.png](https://github.com/EclipseFdn/open-vsx.org/assets/77511070/d4dc5dfc-b89a-4e09-87e6-9de950df8a0d)

I still can see it.

**Comment by kineticsquid** [comment] 2024-02-20 15:32
Weird, I tried again and I do not see this error. @amvanbaren Do you? Thoughts?

**Comment by amvanbaren** [comment] 2024-02-21 14:04
@kineticsquid I'm not getting this error. The extension is deleted.

<details>

<summary>Screenshots</summary>

![dark-minimalist-search](https://github.com/EclipseFdn/open-vsx.org/assets/14129099/8fccd622-e128-4f23-8974-f651d0b277d3)
![dark-minimalist-namespace](https://github.com/EclipseFdn/open-vsx.org/assets/14129099/a941c138-5328-4796-bbd1-2f60e6b72cc0)

</details>


The error is not directly related to deleting an extension. 
@LeonN534 Can you send the console output from the browser developer tools if you're getting the same error on desktop? Maybe that contains more information about the cause of the error.

**Comment by LeonN534** [comment] 2024-02-22 17:03
@amvanbaren I wasn't able to replicate the error on desktop, then I tried using google chrome, since the phones I tested on use it. As expected, the error message seems to appear only on google chrome, not on firefox. This is the console output.

`<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(189, 198, 207); font-family: &quot;dejavu sans mono&quot;, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="webpack://open-vsx/node_modules/openvsx-webui/src/utils.ts:88" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">utils.ts:88</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;"><span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;">DOMException: The user aborted a request.</span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(189, 198, 207); font-family: &quot;dejavu sans mono&quot;, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 11px; --monospace-font-family: dejavu sans mono,monospace; --source-code-font-size: 11px; --source-code-font-family: dejavu sans mono,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | (anonymous) | @ | utils.ts:88
-- | -- | -- | --
  | p | @ | main.tsx:69
  | (anonymous) | @ | extension-list-item.tsx:48
  | l | @ | extension-list-item.tsx:40
  | Promise.then (async) |   |  
  | s | @ | extension-list-item.tsx:40
  | (anonymous) | @ | extension-list-item.tsx:40
  | (anonymous) | @ | extension-list-item.tsx:40
  | i | @ | extension-list-item.tsx:40
  | (anonymous) | @ | extension-list-item.tsx:37
  | os | @ | react-dom.production.min.js:244
  | Ec | @ | react-dom.production.min.js:286
  | cc | @ | react-dom.production.min.js:273
  | Wo | @ | react-dom.production.min.js:127
  | (anonymous) | @ | react-dom.production.min.js:283
  | kc | @ | react-dom.production.min.js:281
  | ac | @ | react-dom.production.min.js:270
  | k | @ | scheduler.production.min.js:13
  | T | @ | scheduler.production.min.js:14

</span></div>`

**Comment by kineticsquid** [comment] 2024-02-26 16:41
@LeonN534 @amvanbaren I see the same thing when I use Chrome:
<img width="1304" alt="image" src="https://github.com/EclipseFdn/open-vsx.org/assets/681707/fdad0c7b-b3eb-4de2-b33a-9996fe2c784a">

**Comment by kineticsquid** [comment] 2024-02-27 19:51
I think this one belongs more in https://github.com/eclipse/openvsx. Closing this one and tracking the 'user abort error' in https://github.com/eclipse/openvsx/issues/863.

**Closed by kineticsquid** 2024-02-27 19:51 UTC
Labels: bug, webui
